export const rooms = [
  {id:'standard',name:'Standard',subtitle:'Всё, что нужно для хорошего отдыха',price:4500,area:24,guests:2,beds:'Двуспальная или две односпальные',image:'/images/standard.jpg',gallery:['/images/standard.jpg','/images/bath.jpg','/images/lounge.jpg'],tag:'Тёплый и уютный',description:'Мягкий утренний свет, натуральные фактуры и удобная кровать. Продуманное пространство для тех, кто ценит простые радости и долгие прогулки у моря.',extras:['Рабочее место','Вид на сад','Климат-контроль','Сейф']},
  {id:'comfort',name:'Comfort',subtitle:'Чуть больше пространства для себя',price:6500,area:32,guests:3,beds:'King-size и дополнительное место',image:'/images/comfort.jpg',gallery:['/images/comfort.jpg','/images/bath.jpg','/images/standard.jpg'],tag:'Больше пространства',description:'Номер, в котором легко почувствовать себя дома. Просторная зона отдыха, текстиль спокойных оттенков и собственный балкон для первой чашки кофе.',extras:['Балкон','Кофемашина','Кресло для чтения','Халаты и тапочки']},
  {id:'deluxe',name:'Deluxe',subtitle:'Утро с видом на горизонт',price:9500,area:42,guests:3,beds:'King-size и диван-кровать',image:'/images/deluxe.jpg',gallery:['/images/deluxe.jpg','/images/bath.jpg','/images/terrace.jpg'],tag:'Панорамный вид',description:'Панорамные окна стирают границу между интерьером и пейзажем. Светлая спальня и отдельная зона отдыха — для красивых утр и вечеров без спешки.',extras:['Панорамные окна','Терраса','Кофемашина','Премиальная косметика']},
  {id:'suite',name:'Suite',subtitle:'Ваше личное пространство у моря',price:14000,area:68,guests:4,beds:'King-size и диван-кровать',image:'/images/suite.jpg',gallery:['/images/suite.jpg','/images/deluxe.jpg','/images/bath.jpg'],tag:'Особенный отдых',description:'Отдельная спальня, просторная гостиная и терраса с шезлонгами. Здесь хватит места для семьи, неспешного завтрака и маленьких отпускных ритуалов.',extras:['Отдельная гостиная','Большая терраса','Ванна и душ','Обеденная зона']}
];
export const services=[
 {id:'breakfast',name:'Завтрак',description:'Каждое утро, 08:00–11:00',price:900,unit:'за гостя / день',image:'/images/breakfast.jpg'},
 {id:'transfer',name:'Трансфер',description:'Встреча в аэропорту',price:2500,unit:'за поездку'},
 {id:'parking',name:'Парковка',description:'Место на закрытой территории',price:500,unit:'за ночь'},
 {id:'early',name:'Ранний заезд',description:'С 09:00, по подтверждению отеля',price:2000,unit:'однократно'},
 {id:'late',name:'Поздний выезд',description:'До 18:00, по подтверждению отеля',price:2000,unit:'однократно'}
];
export const places=[{name:'Морская набережная',type:'Прогулки у воды',distance:'800 м',time:'10 минут пешком',image:'/images/sea.jpg'},{name:'Тропы среди зелени',type:'Природа и свежий воздух',distance:'2,5 км',time:'8 минут на машине',image:'/images/forest.jpg'},{name:'Старый город',type:'Кофейни и локальные места',distance:'4 км',time:'12 минут на машине',image:'/images/terrace.jpg'}];
export const faq=[['Во сколько заезд и выезд?','Заезд с 14:00, выезд до 12:00. Ранний заезд и поздний выезд можно добавить к бронированию; возможность подтвердит администратор.'],['Можно приехать с детьми?','Да. Номера Comfort и Deluxe вмещают до трёх гостей, Suite — до четырёх. Укажите общее количество гостей при поиске.'],['Включён ли завтрак в стоимость?','Завтрак добавляется отдельно: 900 ₽ за гостя в день. Подаём его с 08:00 до 11:00.'],['Как отменить бронирование?','Для отмены обратитесь к администратору, указав номер брони. В демонстрационном проекте можно отменить бронь самостоятельно на странице подтверждения.'],['Нужна ли предоплата?','В этом портфолио-проекте оплата не принимается. После оформления создаётся демонстрационная бронь; реальные правила оплаты настраиваются гостиницей.'],['Есть ли Wi-Fi и парковка?','Wi-Fi включён во всех категориях. Место на закрытой парковке можно добавить за 500 ₽ в сутки.']];
export const money=n=>new Intl.NumberFormat('ru-RU').format(n)+' ₽';
export const dateLabel=s=>{const d=new Date(s+'T12:00:00');return isNaN(d)?'Выберите дату':d.toLocaleDateString('ru-RU',{day:'numeric',month:'short'});};
export function day(offset=0){const d=new Date();d.setDate(d.getDate()+offset);return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`;}
export function nights(a,b){return Math.round((Date.parse(b)-Date.parse(a))/86400000);}
export function total(room,a,b,guests,extras=[]){const n=nights(a,b);return room.price*n+extras.reduce((sum,id)=>{const s=services.find(s=>s.id===id);return sum+(s?s.price*(id==='breakfast'?n*guests:id==='parking'?n:1):0);},0);}

