import {rooms,day,nights,total} from './data.js';
const key='tikhaya-liniya-demo-v1';
export function readStore(){try {const s=JSON.parse(localStorage.getItem(key));if(s?.bookings&&s?.units)return s;}catch{}return {bookings:[],blocks:[],history:[],prices:Object.fromEntries(rooms.map(r=>[r.id,r.price])),units:rooms.flatMap((r,i)=>[1,2,3].map(n=>({id:String((i+1)*100+n),category:r.id,status:'Свободен'})))};}
export function saveStore(s){localStorage.setItem(key,JSON.stringify(s));window.dispatchEvent(new Event('hotel:change'));}
export function overlaps(a,b,c,d){return a<d&&b>c;}
export function validateDates(a,b){const valid=s=>{if(!/^\d{4}-\d{2}-\d{2}$/.test(s))return false;const d=new Date(s);return !isNaN(d)&&d.toISOString().slice(0,10)===s;};return valid(a)&&valid(b)&&a>=day()&&nights(a,b)>0&&nights(a,b)<=30;}
export function availableUnits(store,category,a,b){return store.units.filter(u=>u.category===category&&!['Заселён','Уборка','Забронирован'].includes(u.status)&&!store.blocks.some(x=>x.unit===u.id&&overlaps(a,b,x.from,x.to))&&!store.bookings.some(x=>x.unit===u.id&&x.status!=='Отменено'&&overlaps(a,b,x.arrival,x.departure)));}
export function createDemoBooking(input){const s=readStore();if(!validateDates(input.arrival,input.departure))throw Error('Выберите корректные даты — от 1 до 30 ночей.');const room=rooms.find(r=>r.id===input.category);if(!room||input.guests<1||input.guests>room.guests)throw Error('Проверьте количество гостей.');const unit=availableUnits(s,room.id,input.arrival,input.departure)[0];if(!unit)throw Error('Этот номер уже занят. Выберите другую категорию или даты.');const b={...input,id:'TL-'+crypto.randomUUID().slice(0,8).toUpperCase(),unit:unit.id,status:'Ожидает подтверждения',created:new Date().toISOString(),total:total({...room,price:s.prices[room.id]},input.arrival,input.departure,input.guests,input.extras)};s.bookings.push(b);s.history.unshift({at:new Date().toISOString(),text:`Создана бронь ${b.id}`});saveStore(s);return b;}
export async function getMode(){try{const r=await fetch('/api/config');if(!r.ok)return 'demo';return (await r.json()).mode==='live'?'live':'demo';}catch{return 'demo';}}
export async function request(path,options={}){const r=await fetch(path,{...options,headers:{'Content-Type':'application/json',...options.headers}});const body=await r.json().catch(()=>({error:'Сервис временно недоступен. Попробуйте ещё раз.'}));if(!r.ok)throw Error(body.error||'Не удалось выполнить запрос.');return body;}
