import {randomBytes,createHmac,timingSafeEqual,scryptSync,createHash} from 'node:crypto';
import {rooms,services,nights,total} from '../src/lib/data.js';
export function today(){const d=new Date();return new Intl.DateTimeFormat('sv-SE',{timeZone:'Europe/Moscow',year:'numeric',month:'2-digit',day:'2-digit'}).format(d);}
export function validDate(s){if(typeof s!=='string'||!/^\d{4}-\d{2}-\d{2}$/.test(s))return false;const d=new Date(s);return !isNaN(d)&&d.toISOString().slice(0,10)===s;}
export function validateInput(x){if(!validDate(x.arrival)||!validDate(x.departure)||x.arrival<today()||nights(x.arrival,x.departure)<1||nights(x.arrival,x.departure)>30)throw Error('Выберите даты от 1 до 30 ночей.');const room=rooms.find(r=>r.id===x.category);if(!room||!Number.isInteger(x.guests)||x.guests<1||x.guests>room.guests)throw Error('Проверьте категорию и количество гостей.');if(typeof x.name!=='string'||x.name.trim().length<2||x.name.length>100)throw Error('Введите имя и фамилию.');if(typeof x.phone!=='string'||!/^\+?[\d\s()\-]{10,20}$/.test(x.phone)||x.phone.replace(/\D/g,'').length<10)throw Error('Введите корректный телефон.');if(typeof x.email!=='string'||x.email.length>150||!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(x.email))throw Error('Введите корректный email.');if(x.consent!==true)throw Error('Необходимо согласие на обработку данных.');if(!Array.isArray(x.extras)||x.extras.length>services.length||new Set(x.extras).size!==x.extras.length||x.extras.some(id=>!services.some(s=>s.id===id)))throw Error('Проверьте дополнительные услуги.');return room;}
export function equal(a,b){const aa=Buffer.from(a),bb=Buffer.from(b);return aa.length===bb.length&&timingSafeEqual(aa,bb);}
export function passwordHash(password,salt=randomBytes(16).toString('hex')){return salt+':'+scryptSync(password,salt,64).toString('hex');}
export function passwordValid(password,hash){if(typeof password!=='string'||password.length>256||typeof hash!=='string')return false;const [salt,value]=hash.split(':');if(!salt||!value)return false;return equal(passwordHash(password,salt),hash);}
export function hashToken(token){return createHash('sha256').update(token).digest('hex');}
export function signSession(secret,now=Date.now()){const payload=Buffer.from(JSON.stringify({exp:now+8*3600000,nonce:randomBytes(16).toString('hex')})).toString('base64url');return payload+'.'+createHmac('sha256',secret).update(payload).digest('hex');}
export function sessionValid(token,secret,now=Date.now()){try{if(typeof token!=='string'||!secret)return false;const [p,s]=token.split('.');return equal(s,createHmac('sha256',secret).update(p).digest('hex'))&&JSON.parse(Buffer.from(p,'base64url').toString()).exp>now;}catch{return false;}}
export function configured(){return Boolean(process.env.DATABASE_URL&&process.env.ADMIN_PASSWORD_HASH&&process.env.SESSION_SECRET?.length>=32);}
export {rooms,services,nights,total};
