import {randomUUID} from 'node:crypto';
import {db,json,inputBody,sameOrigin,rateLimit,audit} from '../server/db.js';
import {configured,passwordValid,signSession,sessionValid,validDate,rooms} from '../server/core.js';
export default async function handler(req,res){if(!configured())return json(res,503,{error:'Панель администратора ещё не настроена.'});try{const x=req.method==='POST'?inputBody(req):{};if(req.method==='POST'&&!sameOrigin(req))return json(res,403,{error:'Недопустимый источник запроса.'});if(x.action==='login'){if(!await rateLimit(req,'login',5))return json(res,429,{error:'Слишком много попыток входа. Подождите минуту.'});if(!passwordValid(x.password,process.env.ADMIN_PASSWORD_HASH))return json(res,401,{error:'Неверный пароль.'});res.setHeader('Set-Cookie',`hotel_session=${signSession(process.env.SESSION_SECRET)}; HttpOnly; Secure; SameSite=Strict; Path=/api; Max-Age=28800`);return json(res,200,{ok:true});}const cookie=(req.headers.cookie||'').split(';').find(x=>x.trim().startsWith('hotel_session='))?.trim().slice('hotel_session='.length);if(!sessionValid(cookie,process.env.SESSION_SECRET))return json(res,401,{error:'Войдите в панель администратора.'});if(req.method==='GET'){const sql=db();const [bookings,units,prices,blocks,history]=await Promise.all([sql`select id,unit,category,arrival::text,departure::text,guests,extras,name,phone,email,total,status,created from hotel_bookings order by created desc`,sql`select * from hotel_units order by id`,sql`select * from hotel_prices`,sql`select id,unit,date_from::text as "from",date_to::text as "to" from hotel_blocks order by date_from`,sql`select at,text from hotel_history order by at desc limit 500`]);return json(res,200,{bookings,units,prices:Object.fromEntries(prices.map(p=>[p.category,p.price])),blocks,history});}if(req.method!=='POST'){res.setHeader('Allow','GET, POST');return json(res,405,{error:'Метод не поддерживается.'});}if(x.action==='logout'){res.setHeader('Set-Cookie','hotel_session=; HttpOnly; Secure; SameSite=Strict; Path=/api; Max-Age=0');return json(res,200,{ok:true});}if(!await rateLimit(req,'admin',60))return json(res,429,{error:'Слишком много запросов.'});let text;
if(x.action==='booking'&&['Подтверждено','Отменено'].includes(x.status)){await db().begin(async sql=>{const rows=await sql`select * from hotel_bookings where id=${x.id} for update`;if(!rows.length)throw Error('Бронь не найдена.');if(rows[0].status==='Отменено'&&x.status!=='Отменено')throw Error('Отменённую бронь нельзя подтвердить.');await sql`update hotel_bookings set status=${x.status} where id=${x.id}`;text=`Бронь ${x.id}: ${x.status}`;await audit(sql,text);});}
else if(x.action==='unit'&&['Свободен','Забронирован','Заселён','Уборка'].includes(x.status)){await db().begin(async sql=>{const rows=await sql`update hotel_units set status=${x.status} where id=${x.id} returning id`;if(!rows.length)throw Error('Номер не найден.');text=`Номер ${x.id}: ${x.status}`;await audit(sql,text);});}
else if(x.action==='prices'){if(!x.prices||rooms.some(r=>!Number.isInteger(x.prices[r.id])||x.prices[r.id]<100||x.prices[r.id]>1000000))return json(res,400,{error:'Стоимость должна быть от 100 до 1 000 000 ₽.'});await db().begin(async sql=>{for(const r of rooms)await sql`update hotel_prices set price=${x.prices[r.id]} where category=${r.id}`;await audit(sql,'Тарифы обновлены');});text='Тарифы обновлены';}
else if(x.action==='block'){if(!validDate(x.from)||!validDate(x.to)||x.from>=x.to)return json(res,400,{error:'Проверьте даты блокировки.'});await db().begin(async sql=>{const units=await sql`select * from hotel_units where id=${x.unit} for update`;if(!units.length)throw Error('Номер не найден.');const found=await sql`select id from hotel_bookings where unit=${x.unit} and status<>'Отменено' and arrival<${x.to}::date and departure>${x.from}::date`;if(found.length)throw Error('В этом периоде есть бронь. Сначала отмените её.');await sql`insert into hotel_blocks values (${randomUUID()},${x.unit},${x.from},${x.to})`;text=`Номер ${x.unit} закрыт: ${x.from} — ${x.to}`;await audit(sql,text);});}
else if(x.action==='unblock'){if(typeof x.id!=='string'||!/^[0-9a-f-]{36}$/i.test(x.id))return json(res,400,{error:'Неверная блокировка.'});await db().begin(async sql=>{const b=await sql`delete from hotel_blocks where id=${x.id} returning unit`;if(!b.length)throw Error('Блокировка не найдена.');text=`Снята блокировка номера ${b[0].unit}`;await audit(sql,text);});}
else return json(res,400,{error:'Недопустимое действие.'});return json(res,200,{ok:true,message:text});}catch(e){const safe=['Бронь не найдена.','Номер не найден.','Отменённую бронь нельзя подтвердить.','В этом периоде есть бронь. Сначала отмените её.','Блокировка не найдена.'];if(safe.includes(e.message))return json(res,409,{error:e.message});console.error('Admin request failed');return json(res,500,{error:'Не удалось выполнить действие. Попробуйте ещё раз.'});}}
